import { User, Match, Message, Resource, FilterState, SmokingHabits, DrinkingHabits, MaritalStatus, WillingToRelocate, ChildrenPreference } from './types';

export const CURRENT_USER: User = {
  id: 'user_0',
  name: 'Alex',
  firstName: 'Alex',
  lastName: 'M',
  gender: 'male',
  preferredGender: 'female',
  age: 29,
  bio: 'Software engineer with a passion for travel, hiking, and finding the best coffee shops.',
  interests: ['Traveling', 'Hiking', 'Coffee', 'Programming', 'Photography'],
  profileImageUrls: [
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
  ],
  isVerified: false,
  isPremium: false,
  occupation: 'Software Engineer',
  city: 'San Francisco',
  country: 'USA',
  residenceCountry: 'United States of America',
  residenceState: 'California',
  residenceCity: 'San Francisco',
  originCountry: 'Nigeria',
  originState: 'Lagos',
  originCity: 'Ikeja',
  culturalBackground: 'Yoruba',
  education: 'B.S. in Computer Science',
  languagesSpoken: ['English', 'Yoruba', 'Spanish'],
  religion: 'Christian',
  personalValues: ['Honesty', 'Family', 'Kindness', 'Ambition'],
  smoking: SmokingHabits.NonSmoker,
  drinking: DrinkingHabits.Socially,
  maritalStatus: MaritalStatus.NeverMarried,
  childrenStatus: 'No kids',
  marriageTimeline: '1-2 years',
  willingToRelocate: WillingToRelocate.Maybe,
  preferredMarryFrom: 'Anywhere',
  childrenPreference: ChildrenPreference.WantsChildren,
  idealPartnerTraits: ['Kind', 'Ambitious', 'Family-oriented', 'Good sense of humor'],
  marriageExpectations: 'Looking for a life partner to build a future with, based on shared values, mutual respect, and a deep connection.',
  preferredPartnerAgeRange: [18, 60],
  nationality: 'American/Nigerian',
  careerGoals: 'Lead a team and build a product that makes a difference.',
};

export const MATCHES_DATA: Match[] = [
  {
    id: 'mock-f1',
    name: 'Sarah',
    firstName: 'Sarah',
    lastName: 'Jane',
    gender: 'female',
    preferredGender: 'male',
    age: 27,
    bio: 'Looking for a serious relationship. I love reading and cooking.',
    interests: ['Reading', 'Cooking', 'Travel'],
    profileImageUrls: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400'],
    isVerified: true,
    isPremium: true,
    occupation: 'Teacher',
    city: 'San Francisco',
    country: 'USA',
    residenceCountry: 'USA',
    residenceState: 'CA',
    residenceCity: 'San Francisco',
    originCountry: 'USA',
    originState: 'CA',
    originCity: 'Los Angeles',
    culturalBackground: 'American',
    education: 'Bachelors',
    languagesSpoken: ['English'],
    religion: 'Christian',
    personalValues: ['Family'],
    smoking: SmokingHabits.NonSmoker,
    drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried,
    childrenStatus: 'No kids',
    marriageTimeline: '1-2 years',
    willingToRelocate: WillingToRelocate.Maybe,
    preferredMarryFrom: 'Anywhere',
    childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Honest'],
    marriageExpectations: 'Partnership',
    preferredPartnerAgeRange: [25, 35],
    nationality: 'American',
    careerGoals: 'Principal',
    compatibilityScore: 95
  },
  {
    id: 'mock-f2',
    name: 'Emily',
    firstName: 'Emily',
    lastName: 'Chen',
    gender: 'female',
    preferredGender: 'male',
    age: 26,
    bio: 'Adventurous and spontaneous.',
    interests: ['Hiking', 'Photography'],
    profileImageUrls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400'],
    isVerified: true,
    isPremium: false,
    occupation: 'Designer',
    city: 'San Francisco',
    country: 'USA',
    residenceCountry: 'USA',
    residenceState: 'CA',
    residenceCity: 'San Francisco',
    originCountry: 'USA',
    originState: 'CA',
    originCity: 'San Francisco',
    culturalBackground: 'American',
    education: 'Bachelors',
    languagesSpoken: ['English', 'Mandarin'],
    religion: 'None',
    personalValues: ['Honesty'],
    smoking: SmokingHabits.NonSmoker,
    drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried,
    childrenStatus: 'No kids',
    marriageTimeline: 'Not sure',
    willingToRelocate: WillingToRelocate.Yes,
    preferredMarryFrom: 'Anywhere',
    childrenPreference: ChildrenPreference.OpenToChildren,
    idealPartnerTraits: ['Funny'],
    marriageExpectations: 'Fun',
    preferredPartnerAgeRange: [25, 35],
    nationality: 'American',
    careerGoals: 'Art Director',
    compatibilityScore: 82
  },
  {
    id: 'mock-m1',
    name: 'Michael',
    firstName: 'Michael',
    lastName: 'Smith',
    gender: 'male',
    preferredGender: 'female',
    age: 30,
    bio: 'Software engineer who loves dogs.',
    interests: ['Coding', 'Dogs'],
    profileImageUrls: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400'],
    isVerified: true,
    isPremium: true,
    occupation: 'Engineer',
    city: 'San Francisco',
    country: 'USA',
    residenceCountry: 'USA',
    residenceState: 'CA',
    residenceCity: 'San Francisco',
    originCountry: 'USA',
    originState: 'NY',
    originCity: 'New York',
    culturalBackground: 'American',
    education: 'Masters',
    languagesSpoken: ['English'],
    religion: 'Christian',
    personalValues: ['Family', 'Loyalty'],
    smoking: SmokingHabits.NonSmoker,
    drinking: DrinkingHabits.Never,
    maritalStatus: MaritalStatus.NeverMarried,
    childrenStatus: 'No kids',
    marriageTimeline: 'ASAP',
    willingToRelocate: WillingToRelocate.No,
    preferredMarryFrom: 'Anywhere',
    childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Kind', 'Loyal'],
    marriageExpectations: 'Traditional',
    preferredPartnerAgeRange: [22, 32],
    nationality: 'American',
    careerGoals: 'CTO',
    compatibilityScore: 88
  },
  {
    id: 'mock-m2',
    name: 'David',
    firstName: 'David',
    lastName: 'Jones',
    gender: 'male',
    preferredGender: 'female',
    age: 32,
    bio: 'Entrepreneur, always building.',
    interests: ['Startups', 'Reading'],
    profileImageUrls: ['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=400'],
    isVerified: false,
    isPremium: false,
    occupation: 'Founder',
    city: 'Los Angeles',
    country: 'USA',
    residenceCountry: 'USA',
    residenceState: 'CA',
    residenceCity: 'Los Angeles',
    originCountry: 'USA',
    originState: 'CA',
    originCity: 'Los Angeles',
    culturalBackground: 'American',
    education: 'Bachelors',
    languagesSpoken: ['English'],
    religion: 'Christian',
    personalValues: ['Ambition'],
    smoking: SmokingHabits.Occasional,
    drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried,
    childrenStatus: 'No kids',
    marriageTimeline: '1-2 years',
    willingToRelocate: WillingToRelocate.Yes,
    preferredMarryFrom: 'Anywhere',
    childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Driven'],
    marriageExpectations: 'Supportive',
    preferredPartnerAgeRange: [25, 30],
    nationality: 'American',
    careerGoals: 'CEO',
    compatibilityScore: 75
  },
];

export const INITIAL_FILTERS: FilterState = {
  ageRange: [18, 60],
  location: '',
  showVerifiedOnly: false,
};
