import { User, Match, Message, Resource, FilterState, SmokingHabits, DrinkingHabits, MaritalStatus, WillingToRelocate, ChildrenPreference } from './types';

export const CURRENT_USER: User = {
  id: 'user_0',
  name: 'Alex',
  age: 29,
  bio: 'Software engineer with a passion for travel, hiking, and finding the best coffee shops.',
  interests: ['Traveling', 'Hiking', 'Coffee', 'Programming', 'Photography'],
  profileImageUrls: [
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
  ],
  isVerified: false,
  isPremium: false,
  occupation: 'Software Engineer',
  city: 'San Francisco',
  country: 'USA',
  residenceCountry: 'United States of America',
  residenceState: 'California',
  residenceCity: 'San Francisco',
  originCountry: 'Nigeria',
  originState: 'Lagos',
  originCity: 'Ikeja',
  culturalBackground: 'Yoruba',
  education: 'B.S. in Computer Science',
  languages: ['English', 'Yoruba', 'Spanish'],
  religion: 'Christian',
  personalValues: ['Honesty', 'Family', 'Kindness', 'Ambition'],
  smoking: SmokingHabits.NonSmoker,
  drinking: DrinkingHabits.Socially,
  maritalStatus: MaritalStatus.NeverMarried,
  childrenStatus: 'No kids',
  marriageTimeline: '1-2 years',
  willingToRelocate: WillingToRelocate.Maybe,
  preferredMarryFrom: 'Anywhere',
  childrenPreference: ChildrenPreference.WantsChildren,
  idealPartnerTraits: ['Kind', 'Ambitious', 'Family-oriented', 'Good sense of humor'],
  marriageExpectations: 'Looking for a life partner to build a future with, based on shared values, mutual respect, and a deep connection.',
  preferredPartnerAgeRange: [18, 60],
  nationality: 'American/Nigerian',
  careerGoals: 'Lead a team and build a product that makes a difference.',
};

export const MATCHES_DATA: Match[] = [
  {
    id: 'match_1', name: 'Sofia', age: 27,
    bio: "Art director who loves painting, visiting museums, and trying new recipes.",
    interests: ['Art', 'Cooking', 'Museums', 'Traveling', 'Yoga'],
    profileImageUrls: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop'],
    isVerified: true, isPremium: true, subscriptionAmount: 10.00,
    occupation: 'Art Director', city: 'New York', country: 'USA',
    residenceCountry: 'United States of America', residenceState: 'New York', residenceCity: 'New York',
    originCountry: 'Italy', originState: 'Tuscany', originCity: 'Florence',
    culturalBackground: 'Italian',
    marriageExpectations: 'Seeking a genuine connection with someone who is passionate about their life.',
    preferredPartnerAgeRange: [25, 35],
    education: 'M.A. in Fine Arts', languages: ['English', 'French', 'Italian'],
    religion: 'Spiritual but not religious', personalValues: ['Creativity', 'Empathy', 'Growth'],
    smoking: SmokingHabits.NonSmoker, drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried, childrenStatus: 'No kids',
    marriageTimeline: 'Within a year', willingToRelocate: WillingToRelocate.Yes,
    preferredMarryFrom: 'USA, Europe', childrenPreference: ChildrenPreference.OpenToChildren,
    idealPartnerTraits: ['Creative', 'Kind', 'Supportive'], nationality: 'American',
    careerGoals: 'Open my own art gallery.',
  },
  {
    id: 'match_2', name: 'Liam', age: 31,
    bio: 'Doctor who unwinds by playing guitar and going for long runs.',
    interests: ['Music', 'Running', 'Reading', 'Volunteering'],
    profileImageUrls: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&auto=format&fit=crop'],
    isVerified: true, isPremium: true, subscriptionAmount: 7.00,
    occupation: 'Doctor', city: 'London', country: 'UK',
    residenceCountry: 'United Kingdom', residenceState: 'England', residenceCity: 'London',
    originCountry: 'United Kingdom', originState: 'Scotland', originCity: 'Edinburgh',
    culturalBackground: 'Scottish-British',
    marriageExpectations: "I'm looking for a partner in life who is caring, intelligent.",
    preferredPartnerAgeRange: [26, 34],
    education: 'MD', languages: ['English'], religion: 'Agnostic',
    personalValues: ['Compassion', 'Family', 'Intellect'],
    smoking: SmokingHabits.NonSmoker, drinking: DrinkingHabits.Never,
    maritalStatus: MaritalStatus.Divorced, childrenStatus: 'Has children',
    marriageTimeline: '1-2 years', willingToRelocate: WillingToRelocate.No,
    preferredMarryFrom: 'UK', childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Caring', 'Intelligent', 'Family-oriented'], nationality: 'British',
    careerGoals: 'Specialize in pediatric care.',
  },
  {
    id: 'match_3', name: 'Amina', age: 26,
    bio: 'Architectural designer with a love for sustainable living and traditional crafts.',
    interests: ['Architecture', 'Sustainability', 'History', 'Reading'],
    profileImageUrls: ['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=800&auto=format&fit=crop'],
    isVerified: true, isPremium: true, subscriptionAmount: 10.00,
    occupation: 'Architect', city: 'Lagos', country: 'Nigeria',
    residenceCountry: 'Nigeria', residenceState: 'Lagos', residenceCity: 'Lagos',
    originCountry: 'Nigeria', originState: 'Oyo', originCity: 'Ibadan',
    culturalBackground: 'Yoruba',
    marriageExpectations: 'I seek a partner who values faith, family, and shared growth.',
    preferredPartnerAgeRange: [28, 35],
    education: 'M.Sc. Architecture', languages: ['English', 'Yoruba'],
    religion: 'Muslim', personalValues: ['Faith', 'Integrity', 'Family'],
    smoking: SmokingHabits.NonSmoker, drinking: DrinkingHabits.Never,
    maritalStatus: MaritalStatus.NeverMarried, childrenStatus: 'No kids',
    marriageTimeline: '1-2 years', willingToRelocate: WillingToRelocate.Maybe,
    preferredMarryFrom: 'Nigeria, UK, USA', childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['God-fearing', 'Ambitious', 'Kind'], nationality: 'Nigerian',
    careerGoals: 'Design eco-friendly housing projects.',
  },
  {
    id: 'match_4', name: 'Chen', age: 30,
    bio: 'Financial analyst who enjoys martial arts and classical music.',
    interests: ['Finance', 'Kung Fu', 'Piano', 'Travel'],
    profileImageUrls: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop'],
    isVerified: true, isPremium: false, subscriptionAmount: 0,
    occupation: 'Financial Analyst', city: 'Shanghai', country: 'China',
    residenceCountry: 'China', residenceState: 'Shanghai', residenceCity: 'Shanghai',
    originCountry: 'China', originState: 'Zhejiang', originCity: 'Hangzhou',
    culturalBackground: 'Han Chinese',
    marriageExpectations: 'Looking for a supportive partner to build a stable and happy family life.',
    preferredPartnerAgeRange: [24, 30],
    education: 'MBA', languages: ['Mandarin', 'English'], religion: 'Buddhist',
    personalValues: ['Respect', 'Stability', 'Loyalty'],
    smoking: SmokingHabits.NonSmoker, drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried, childrenStatus: 'No kids',
    marriageTimeline: '2-3 years', willingToRelocate: WillingToRelocate.Yes,
    preferredMarryFrom: 'Anywhere', childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Intelligent', 'Family-oriented', 'Gentle'], nationality: 'Chinese',
    careerGoals: 'Become a senior portfolio manager.',
  },
  {
    id: 'match_5', name: 'Priya', age: 28,
    bio: 'Software developer and amateur photographer.',
    interests: ['Photography', 'Coding', 'Hiking', 'Street Food'],
    profileImageUrls: ['https://images.unsplash.com/photo-1514626585111-9aa86183ac98?q=80&w=800&auto=format&fit=crop'],
    isVerified: true, isPremium: true, subscriptionAmount: 7.00,
    occupation: 'Software Engineer', city: 'Mumbai', country: 'India',
    residenceCountry: 'India', residenceState: 'Maharashtra', residenceCity: 'Mumbai',
    originCountry: 'India', originState: 'Karnataka', originCity: 'Bangalore',
    culturalBackground: 'South Indian',
    marriageExpectations: 'I want a partner who is also a best friend.',
    preferredPartnerAgeRange: [27, 34],
    education: 'B.Tech Computer Science', languages: ['English', 'Hindi', 'Kannada'],
    religion: 'Hindu', personalValues: ['Honesty', 'Humor', 'Ambition'],
    smoking: SmokingHabits.NonSmoker, drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried, childrenStatus: 'No kids',
    marriageTimeline: '1-2 years', willingToRelocate: WillingToRelocate.Maybe,
    preferredMarryFrom: 'India, USA, UK', childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Supportive', 'Funny', 'Ambitious'], nationality: 'Indian',
    careerGoals: 'Launch my own tech startup.',
  },
];

export const INITIAL_FILTERS: FilterState = {
  ageRange: [18, 60],
  location: '',
  showVerifiedOnly: false,
};
