
import { User, Match, Resource, FilterState, SmokingHabits, DrinkingHabits, MaritalStatus, WillingToRelocate, ChildrenPreference, Message } from './types';

export const CURRENT_USER: User = {
    id: 'user_0',
    name: 'Alex',
    age: 29,
    bio: "Software engineer with a passion for travel, hiking, and finding the best coffee shops. Looking for someone to share adventures and quiet moments with. My faith and family are important to me.",
    interests: ["Traveling", "Hiking", "Coffee", "Programming", "Photography"],
    profileImageUrls: [
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop',
    ],
    isVerified: false,
    isPremium: false,
    occupation: 'Software Engineer',
    city: 'San Francisco',
    country: 'USA',
    // Detailed Registry Locations
    residenceCountry: 'United States of America',
    residenceState: 'California',
    residenceCity: 'San Francisco',
    originCountry: 'Nigeria',
    originState: 'Lagos',
    originCity: 'Ikeja',
    culturalBackground: 'Yoruba',
    education: 'B.S. in Computer Science',
    languages: ['English', 'Yoruba', 'Spanish'],
    religion: 'Christian',
    personalValues: ['Honesty', 'Family', 'Kindness', 'Ambition'],
    smoking: SmokingHabits.NonSmoker,
    drinking: DrinkingHabits.Socially,
    maritalStatus: MaritalStatus.NeverMarried,
    childrenStatus: "No kids",
    marriageTimeline: '1-2 years',
    willingToRelocate: WillingToRelocate.Maybe,
    preferredMarryFrom: 'Anywhere',
    childrenPreference: ChildrenPreference.WantsChildren,
    idealPartnerTraits: ['Kind', 'Ambitious', 'Family-oriented', 'Good sense of humor'],
    marriageExpectations: "Looking for a life partner to build a future with, based on shared values, mutual respect, and a deep connection.",
    preferredPartnerAgeRange: [18, 60],
    nationality: 'American/Nigerian',
    careerGoals: 'Lead a team and build a product that makes a difference.'
};

export const MATCHES_DATA: Match[] = [
    {
        id: 'match_1',
        name: 'Sofia',
        age: 27,
        bio: "Art director who loves painting, visiting museums, and trying new recipes. I'm looking for a creative and kind-hearted partner to explore life with.",
        interests: ["Art", "Cooking", "Museums", "Traveling", "Yoga"],
        profileImageUrls: [
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop', 
            'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=800&auto=format&fit=crop'
        ],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 10.00,
        occupation: 'Art Director',
        city: 'New York',
        country: 'USA',
        residenceCountry: 'United States of America',
        residenceState: 'New York',
        residenceCity: 'New York',
        originCountry: 'Italy',
        originState: 'Tuscany',
        originCity: 'Florence',
        culturalBackground: 'Italian',
        marriageExpectations: "Seeking a genuine connection with someone who is passionate about their life and is ready for a serious commitment.",
        preferredPartnerAgeRange: [25, 35],
        education: 'M.A. in Fine Arts',
        languages: ['English', 'French', 'Italian'],
        religion: 'Spiritual but not religious',
        personalValues: ['Creativity', 'Empathy', 'Growth'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: 'Within a year',
        willingToRelocate: WillingToRelocate.Yes,
        preferredMarryFrom: 'USA, Europe',
        childrenPreference: ChildrenPreference.OpenToChildren,
        idealPartnerTraits: ['Creative', 'Kind', 'Supportive'],
        nationality: 'American',
        careerGoals: 'Open my own art gallery.'
    },
    {
        id: 'match_2',
        name: 'Liam',
        age: 31,
        bio: "Doctor who unwinds by playing guitar and going for long runs. I value deep conversations and a good sense of humor. Family is very important to me.",
        interests: ["Music", "Running", "Reading", "Volunteering"],
        profileImageUrls: [
            'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&auto=format&fit=crop', 
            'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop', 
            'https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=800&auto=format&fit=crop'
        ],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 7.00,
        occupation: 'Doctor',
        city: 'London',
        country: 'UK',
        residenceCountry: 'United Kingdom',
        residenceState: 'England',
        residenceCity: 'London',
        originCountry: 'United Kingdom',
        originState: 'Scotland',
        originCity: 'Edinburgh',
        culturalBackground: 'Scottish-British',
        marriageExpectations: "I'm looking for a partner in life who is caring, intelligent, and shares my desire to build a family.",
        preferredPartnerAgeRange: [26, 34],
        education: 'MD',
        languages: ['English'],
        religion: 'Agnostic',
        personalValues: ['Compassion', 'Family', 'Intellect'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Never,
        maritalStatus: MaritalStatus.Divorced,
        childrenStatus: "Has children",
        marriageTimeline: '1-2 years',
        willingToRelocate: WillingToRelocate.No,
        preferredMarryFrom: 'UK',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Caring', 'Intelligent', 'Family-oriented'],
        nationality: 'British',
        careerGoals: 'Specialize in pediatric care.'
    },
    {
        id: 'match_3',
        name: 'Amina',
        age: 26,
        bio: "Architectural designer with a love for sustainable living and traditional crafts. I enjoy weekend trips to historic sites and quiet evenings with a good book.",
        interests: ["Architecture", "Sustainability", "History", "Reading"],
        profileImageUrls: ['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 10.00,
        occupation: 'Architect',
        city: 'Lagos',
        country: 'Nigeria',
        residenceCountry: 'Nigeria',
        residenceState: 'Lagos',
        residenceCity: 'Lagos',
        originCountry: 'Nigeria',
        originState: 'Oyo',
        originCity: 'Ibadan',
        culturalBackground: 'Yoruba',
        marriageExpectations: "I seek a partner who values faith, family, and shared growth. Someone who is ready to build a home rooted in mutual respect.",
        preferredPartnerAgeRange: [28, 35],
        education: 'M.Sc. Architecture',
        languages: ['English', 'Yoruba'],
        religion: 'Muslim',
        personalValues: ['Faith', 'Integrity', 'Family'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Never,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '1-2 years',
        willingToRelocate: WillingToRelocate.Maybe,
        preferredMarryFrom: 'Nigeria, UK, USA',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['God-fearing', 'Ambitious', 'Kind'],
        nationality: 'Nigerian',
        careerGoals: 'Design eco-friendly housing projects.'
    },
    {
        id: 'match_4',
        name: 'Chen',
        age: 30,
        bio: "Financial analyst who enjoys martial arts and classical music. I'm a balanced person who values tradition but embraces modern life.",
        interests: ["Finance", "Kung Fu", "Piano", "Travel"],
        profileImageUrls: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: false,
        subscriptionAmount: 0,
        occupation: 'Financial Analyst',
        city: 'Shanghai',
        country: 'China',
        residenceCountry: 'China',
        residenceState: 'Shanghai',
        residenceCity: 'Shanghai',
        originCountry: 'China',
        originState: 'Zhejiang',
        originCity: 'Hangzhou',
        culturalBackground: 'Han Chinese',
        marriageExpectations: "Looking for a supportive partner to build a stable and happy family life. Shared values and mutual support are key.",
        preferredPartnerAgeRange: [24, 30],
        education: 'MBA',
        languages: ['Mandarin', 'English'],
        religion: 'Buddhist',
        personalValues: ['Respect', 'Stability', 'Loyalty'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '2-3 years',
        willingToRelocate: WillingToRelocate.Yes,
        preferredMarryFrom: 'Anywhere',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Intelligent', 'Family-oriented', 'Gentle'],
        nationality: 'Chinese',
        careerGoals: 'Become a senior portfolio manager.'
    },
    {
        id: 'match_5',
        name: 'Priya',
        age: 28,
        bio: "Software developer and amateur photographer. I love exploring hidden gems in the city and capturing moments. I'm looking for someone who appreciates the small things.",
        interests: ["Photography", "Coding", "Hiking", "Street Food"],
        profileImageUrls: ['https://images.unsplash.com/photo-1514626585111-9aa86183ac98?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 7.00,
        occupation: 'Software Engineer',
        city: 'Mumbai',
        country: 'India',
        residenceCountry: 'India',
        residenceState: 'Maharashtra',
        residenceCity: 'Mumbai',
        originCountry: 'India',
        originState: 'Karnataka',
        originCity: 'Bangalore',
        culturalBackground: 'South Indian',
        marriageExpectations: "I want a partner who is also a best friend. Someone I can grow with and build a life full of laughter and shared dreams.",
        preferredPartnerAgeRange: [27, 34],
        education: 'B.Tech Computer Science',
        languages: ['English', 'Hindi', 'Kannada'],
        religion: 'Hindu',
        personalValues: ['Honesty', 'Humor', 'Ambition'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '1-2 years',
        willingToRelocate: WillingToRelocate.Maybe,
        preferredMarryFrom: 'India, USA, UK',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Supportive', 'Funny', 'Ambitious'],
        nationality: 'Indian',
        careerGoals: 'Launch my own tech startup.'
    },
    {
        id: 'match_6',
        name: 'Mateo',
        age: 33,
        bio: "Chef de cuisine with a passion for Mediterranean flavors. I love hosting dinner parties and sharing stories through food. Looking for someone to share life's flavors with.",
        interests: ["Cooking", "Wine", "Travel", "Sailing"],
        profileImageUrls: ['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 10.00,
        occupation: 'Executive Chef',
        city: 'Barcelona',
        country: 'Spain',
        residenceCountry: 'Spain',
        residenceState: 'Catalonia',
        residenceCity: 'Barcelona',
        originCountry: 'Spain',
        originState: 'Andalusia',
        originCity: 'Seville',
        culturalBackground: 'Spanish',
        marriageExpectations: "Seeking a partner who appreciates the art of living. Someone who values family, tradition, and good food.",
        preferredPartnerAgeRange: [25, 33],
        education: 'Culinary Arts Degree',
        languages: ['Spanish', 'English', 'Catalan'],
        religion: 'Catholic',
        personalValues: ['Passion', 'Family', 'Creativity'],
        smoking: SmokingHabits.Occasional,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: 'Within a year',
        willingToRelocate: WillingToRelocate.Maybe,
        preferredMarryFrom: 'Europe',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Vibrant', 'Kind', 'Family-oriented'],
        nationality: 'Spanish',
        careerGoals: 'Earn a Michelin star for my restaurant.'
    },
    {
        id: 'match_7',
        name: 'Yuki',
        age: 29,
        bio: "Graphic designer who loves minimalist aesthetics and Japanese tea ceremonies. I'm a calm person looking for a peaceful and meaningful connection.",
        interests: ["Design", "Tea Ceremony", "Gardening", "Reading"],
        profileImageUrls: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: false,
        subscriptionAmount: 0,
        occupation: 'Graphic Designer',
        city: 'Tokyo',
        country: 'Japan',
        residenceCountry: 'Japan',
        residenceState: 'Tokyo',
        residenceCity: 'Tokyo',
        originCountry: 'Japan',
        originState: 'Kyoto',
        originCity: 'Kyoto',
        culturalBackground: 'Japanese',
        marriageExpectations: "I value harmony and mutual respect. I'm looking for a partner to build a quiet, beautiful life with.",
        preferredPartnerAgeRange: [28, 36],
        education: 'B.A. in Design',
        languages: ['Japanese', 'English'],
        religion: 'Shinto',
        personalValues: ['Harmony', 'Simplicity', 'Respect'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Never,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '2-3 years',
        willingToRelocate: WillingToRelocate.No,
        preferredMarryFrom: 'Japan',
        childrenPreference: ChildrenPreference.OpenToChildren,
        idealPartnerTraits: ['Calm', 'Considerate', 'Sincere'],
        nationality: 'Japanese',
        careerGoals: 'Publish a book on minimalist design.'
    },
    {
        id: 'match_8',
        name: 'Kofi',
        age: 32,
        bio: "Civil engineer who loves high-life music and community building. I'm a social person who values my roots and looks forward to building a future.",
        interests: ["Engineering", "Music", "Community", "Sports"],
        profileImageUrls: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 7.00,
        occupation: 'Civil Engineer',
        city: 'Accra',
        country: 'Ghana',
        residenceCountry: 'Ghana',
        residenceState: 'Greater Accra',
        residenceCity: 'Accra',
        originCountry: 'Ghana',
        originState: 'Ashanti',
        originCity: 'Kumasi',
        culturalBackground: 'Akan',
        marriageExpectations: "I'm looking for a woman who is strong, kind, and shares my values. Family and community are the pillars of my life.",
        preferredPartnerAgeRange: [24, 30],
        education: 'B.Sc. Civil Engineering',
        languages: ['English', 'Twi'],
        religion: 'Christian',
        personalValues: ['Community', 'Loyalty', 'Hard work'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '1-2 years',
        willingToRelocate: WillingToRelocate.Maybe,
        preferredMarryFrom: 'Ghana, UK, USA',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Kind', 'Respectful', 'Ambitious'],
        nationality: 'Ghanaian',
        careerGoals: 'Lead major infrastructure projects in West Africa.'
    },
    {
        id: 'match_9',
        name: 'Elena',
        age: 27,
        bio: "Journalist with a passion for storytelling and human rights. I love traveling to off-the-beaten-path locations and learning about different cultures.",
        interests: ["Journalism", "Travel", "Human Rights", "Languages"],
        profileImageUrls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: true,
        subscriptionAmount: 10.00,
        occupation: 'Journalist',
        city: 'Berlin',
        country: 'Germany',
        residenceCountry: 'Germany',
        residenceState: 'Berlin',
        residenceCity: 'Berlin',
        originCountry: 'Russia',
        originState: 'Moscow',
        originCity: 'Moscow',
        culturalBackground: 'Russian',
        marriageExpectations: "I seek an adventurous and open-minded partner. Someone who is ready to explore the world and build a life of purpose together.",
        preferredPartnerAgeRange: [27, 35],
        education: 'M.A. in Journalism',
        languages: ['Russian', 'English', 'German'],
        religion: 'Orthodox Christian',
        personalValues: ['Truth', 'Adventure', 'Empathy'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Socially,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '2-3 years',
        willingToRelocate: WillingToRelocate.Yes,
        preferredMarryFrom: 'Europe, USA',
        childrenPreference: ChildrenPreference.OpenToChildren,
        idealPartnerTraits: ['Intelligent', 'Adventurous', 'Kind'],
        nationality: 'Russian/German',
        careerGoals: 'Write for a major international news outlet.'
    },
    {
        id: 'match_10',
        name: 'Omar',
        age: 34,
        bio: "Entrepreneur in the tech space. I value innovation, hard work, and family. I'm looking for a partner who is equally ambitious and supportive.",
        interests: ["Tech", "Business", "Fitness", "Travel"],
        profileImageUrls: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop'],
        isVerified: true,
        isPremium: false,
        subscriptionAmount: 0,
        occupation: 'Tech Entrepreneur',
        city: 'Dubai',
        country: 'UAE',
        residenceCountry: 'United Arab Emirates',
        residenceState: 'Dubai',
        residenceCity: 'Dubai',
        originCountry: 'Lebanon',
        originState: 'Beirut',
        originCity: 'Beirut',
        culturalBackground: 'Lebanese',
        marriageExpectations: "I'm looking for a life partner who can be my equal. Someone to share the highs and lows of building a future together.",
        preferredPartnerAgeRange: [25, 32],
        education: 'B.S. in Economics',
        languages: ['Arabic', 'English', 'French'],
        religion: 'Muslim',
        personalValues: ['Ambition', 'Loyalty', 'Family'],
        smoking: SmokingHabits.NonSmoker,
        drinking: DrinkingHabits.Never,
        maritalStatus: MaritalStatus.NeverMarried,
        childrenStatus: "No kids",
        marriageTimeline: '1-2 years',
        willingToRelocate: WillingToRelocate.Maybe,
        preferredMarryFrom: 'Middle East, Europe',
        childrenPreference: ChildrenPreference.WantsChildren,
        idealPartnerTraits: ['Ambitious', 'Supportive', 'Intelligent'],
        nationality: 'Lebanese',
        careerGoals: 'Take my company public.'
    }
];

export const LIKED_MATCHES_DATA: Match[] = [
    MATCHES_DATA[0]
];

export const MESSAGES_DATA: { matchId: string, messages: Message[] }[] = [
    {
        matchId: 'match_1',
        messages: [
            { id: 'msg1', senderId: 'match_1', text: `Hey ${CURRENT_USER.name}! It's great to connect.`, timestamp: new Date(Date.now() - 1000 * 60 * 10) },
        ]
    }
];

export const RESOURCES_DATA: Resource[] = [
    {
        id: 'res1',
        title: '5 Tips for a Great First Date',
        description: 'Make a lasting impression with these proven first date tips.',
        category: 'Dating Advice',
        imageUrl: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?q=80&w=800&auto=format&fit=crop',
        link: '#'
    }
];

export const INITIAL_FILTERS: FilterState = {
    ageRange: [18, 60],
    location: '',
    showVerifiedOnly: false,
};
